### ISSUE TITLE
'Worksheet' object has no attribute 'to_csv' when use gspread.authorize to get the spreadsheet

### ISSUE THREAD

**Issue by aerilxx** [xflr6/gsheets#10]
I'm trying to dump a work to csv, I use _oauth2client.service_account_ to access spreadsheet obj with local json key credentials.  I am able to fetch all spreadsheet but cannot dump to csv.

code below:
`scope = ['https://www.googleapis.com/auth/spreadsheets', "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name('key.json', scope)
client = gspread.authorize(creds)
key_pair = client.open("test").sheet1
key_pair.to_csv('Spam.csv', encoding='utf-8', dialect='excel')
`

error:
> key_pair.to_csv('Spam.csv', encoding='utf-8', dialect='excel')
AttributeError: 'Worksheet' object has no attribute 'to_csv'

Do I have to use url/id to fetch a worksheet to make it valid for to_csv?

**Comment by xflr6** [comment]
AFAICT you are using [gspread](https://github.com/burnash/gspread) (i.e. not this librabry `gsheets`). Not sure if the former has a [method for CSV export](https://gspread.readthedocs.io/en/latest/api.html) though. See the [documentation here](https://gsheets.readthedocs.io) for an example of this libaries' usage.

**Comment by aerilxx** [comment]
yes I'm using `gspread` just to get credential from googlespreadsheet api and access worksheet. but as long as I get access the worksheet and import `gsheets`, I should still be able to use `to_csv`func here right?

**Comment by xflr6** [comment]
No, because you are instantiating a client from `gspread.authorize(creds)`. If `creds` are OAuth credentials, you might be able to use `gsheets.Sheets(creds)` ([documentation](https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets)).

Not sure if you need to use `gspread` for the credentials, did you check [Sheets.from_files()](https://gsheets.readthedocs.io/en/stable/api.html#gsheets.Sheets.from_files)?
