### ISSUE TITLE
Accessing Google Sheets using service account

### ISSUE THREAD

**Issue by stephenhky** [xflr6/gsheets#24]
Since I am developing something on AWS Lambda, I need the API to be able to access Google Sheets using service account. I saw Sheets can only access using API Key and client_json credential files... is it possible to use service account?

**Comment by jjlatval** [comment]
I was looking at this repository and saw a recent question so I decided to comment because I just implemented a system where a service account is used to periodically download certain Google sheets as .csv files using Google Sheets API v4. You will need to create a service account, get a JSON file that contains service account credentials and then grant access to the created service account to desired resources in Google Drive. You will need to install some third-party libraries, e.g. **google-api-python-client**, **google-auth-httplib2** and **google-auth-oauthlib**. Here is my implementation:

```
import csv
from typing import Sequence

from googleapiclient import discovery
from google.oauth2 import service_account
from config import GOOGLE_SHEETS_CREDENTIALS_PATH

SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets.readonly"
]

class GoogleSheetsAPIRequest:

    def __init__(self, credentials_fpath: str = GOOGLE_SHEETS_CREDENTIALS_PATH, scopes: Sequence[str] = None) -> None:
        scopes = scopes or SCOPES
        credentials = service_account.Credentials.from_service_account_file(credentials_fpath, scopes=scopes)
        self.service = discovery.build("sheets", "v4", credentials=credentials)

    def download_sheet_to_csv(self, spreadsheet_id: str, tab_name: str, output_fpath: str, **kwargs) -> None:
        result = self.service.spreadsheets().values().get(spreadsheetId=spreadsheet_id, range=tab_name).execute()
        output_file = output_fpath if output_fpath.endswith(".csv") else output_fpath + ".csv"
        with open(output_file, "w") as f:
            writer = csv.writer(f, delimiter=kwargs.get("sep", ","), quotechar=kwargs.get("quotechar", "\""),
                                quoting=kwargs.get("quoting", csv.QUOTE_ALL), escapechar=kwargs.get("escapechar", "\\"))
            writer.writerows(result.get("values"))
        f.close()
```

**Comment by stephenhky** [comment]
Thanks! I made a similar solution to get around from it as well: https://github.com/stephenhky/SSSpend/blob/master/ssspend/spenddataframe.py#L18
