### ISSUE TITLE
Create multiple link in a single row

### ISSUE THREAD

**Issue by erwin-d-austria** [xflr6/gsheets#27]
Is gsheets can create multiple link in single cell like this on on google SpreadsheetApp.

const value = SpreadsheetApp.newRichTextValue()
.setText("foo no baz")
.setLinkUrl(0, 3, "https://bar.foo/")
.setLinkUrl(7, 10, "https://abc.xyz/")
.setTextStyle(7, 10, boldStyle)
.build();

**Comment by ItsMeSamey** [comment]
`import pygsheets
client = pygsheets.authorize()
# Open the spreadsheet and the first sheet.
sh = client.open('spreadsheet-title')
wks = sh.sheet1

header = wks.cell('A1') # you can use tuple too instead of string as wks.cell((1,1))
header.value = 'foo not bar'
header.text_format['bold'] = True # make the header bold
header.update() # update cell values

header2 = wks.cell('A2')
header2.formula = 'HYPERLINK("http://www.google.com/","Google")'#use double quotes surrounding link and title ,"Google" not 'Google'
`
For more documentation read [Pygsheets docs](https://pygsheets.readthedocs.io/en/staging/index.html) 
And google sheet's [Hyperlink docs](https://support.google.com/docs/answer/3093313?hl=en)
